version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    platform: linux/arm64
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: backend2
      DB_USER: admin
      DB_PASSWORD: iceamericano
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 1234
    volumes:
      - ./build/libs/keycloak-user-storage-jpa.jar:/opt/keycloak/providers/keycloak-user-storage-jpa.jar
      - ./conf/quarkus-prod.properties:/opt/keycloak/conf/quarkus.properties
      - ./ObjectStore/:/ObjectStore/
      - ./themes:/opt/keycloak/themes/custom/
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
