version: '3.8'
services:
  mysql:
    image: mysql:8.0
    platform: linux/arm64
    environment:
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: test1234
      MYSQL_ROOT_PASSWORD: test1234
    ports:
      - "3306:3306"
    healthcheck:
      test: [ 'CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD' ]
      interval: 20s
      retries: 3
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    platform: linux/arm64
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: test1234
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 1234
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./build/libs/keycloak-user-storage-jpa.jar:/opt/keycloak/providers/keycloak-user-storage-jpa.jar
      - ./conf/quarkus.properties:/opt/keycloak/conf/quarkus.properties
      - ./ObjectStore/:/ObjectStore/
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3

