name: "버그 레포트"
description: "Thank you for reporting a bug!"
body:
  - type: markdown
    attributes:
      value: |
        버그 레포트
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 0.0.1 (Snapshot)
    validations:
      required: true
  - type: checkboxes
    id: priority
    attributes:
      label: Priority Label Setting
      description: Priority Label 지정하셨나요?
      options:
        - label: Yes! Priority Label 지정했습니다.
          required: true
  - type: checkboxes
    id: projects
    attributes:
      label: Projects Card
      description: Project Card 생성하셨나요?
      options:
        - label: Yes! 생성했습니다.
          required: true
