spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://login.socoa.online:8080/realms/master
      client:
        provider:
          keycloak:
            issuer-uri: http://login.socoa.online:8080/realms/master
        registration:
          keycloak:
            redirect-uri: "http://login.socoa.online:8080/login/oauth2/code/keycloak"
          google:
            redirect-uri: "http://login.socoa.online:8080/realms/master/broker/google/endpoint"
          github:
            redirect-uri: "http://login.socoa.online:8080/realms/master/broker/github/endpoint"

keycloak:
  realm: master
  client-url: http://login.socoa.online
  server-url: http://login.socoa.online:8080
  auth-server-url: http://login.socoa.online:8080/auth
  ssl-required: external
  resource: admin-client
  credentials:
    secret: admin-secret
  use-resource-role-mappings: true
  bearer-only: true
  logout-url: http://login.socoa.online:8080/realms/master/protocol/openid-connect/logout
  logout-redirect-url: http://login.socoa.online:8080/realms/master/protocol/openid-connect/logout?post_logout_redirect_uri=http://socoa.online/&client_id=admin-client

socoa:
  domain: socoa.online
  gateway:
    url: http://gateway.socoa.online:8000
