server:
  domain: login.socoa.online

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${server.domain}:8080/realms/master
      client:
        provider:
          keycloak:
            issuer-uri: http://${server.domain}:8080/realms/master
        registration:
          keycloak:
            redirect-uri: "http://${server.domain}:8080/login/oauth2/code/keycloak"
          google:
            redirect-uri: "http://${server.domain}:8080/realms/master/broker/google/endpoint"
          github:
            redirect-uri: "http://${server.domain}:8080/realms/master/broker/github/endpoint"

keycloak:
  client-url: http://${server.domain}
  server-url: http://${server.domain}:8080

socoa:
  domain: socoa.online
  gateway:
    url: http://gateway.socoa.online:8000
