server:
  port: 80

keycloak:
  server:
    url: http://localhost:8080
  realm: master
  client:
    id: admin-cli
  admin:
    name: admin
    password: 1234

spring:
  application:
  name: springboot-keycloak

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/auth/realms/CustomSSO/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: sso-client
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG